name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/frame_7011.png
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/group_13_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/group_10_x2.svg
  - assets/vectors/group_15_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/union_9_x2.svg
  - assets/vectors/group_436501_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/group_9_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/polygon_4_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/union_6_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/images/image_11.png
  - assets/images/image_2.png
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/group_5_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/group_4_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/group_43534_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/union_10_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/ellipse_30_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/group_43626_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/group_435342_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/group_435341_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/ellipse_5_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/ellipse_4_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/group_12_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/union_1_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/group_11_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/group_6_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/group_8_x2.svg
  - assets/vectors/group_7_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/ellipse_3_x2.svg
  - assets/vectors/group_43661_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/group_43650_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/group_14_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/union_2_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/images/frame_7011.png
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/union_7_x2.svg
  - assets/vectors/vector_92_x2.svg

